// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chat_backend/internal/model"
)

func newGroupJoinRequest(db *gorm.DB, opts ...gen.DOOption) groupJoinRequest {
	_groupJoinRequest := groupJoinRequest{}

	_groupJoinRequest.groupJoinRequestDo.UseDB(db, opts...)
	_groupJoinRequest.groupJoinRequestDo.UseModel(&model.GroupJoinRequest{})

	tableName := _groupJoinRequest.groupJoinRequestDo.TableName()
	_groupJoinRequest.ALL = field.NewAsterisk(tableName)
	_groupJoinRequest.ID = field.NewUint(tableName, "id")
	_groupJoinRequest.CreatedAt = field.NewTime(tableName, "created_at")
	_groupJoinRequest.UpdatedAt = field.NewTime(tableName, "updated_at")
	_groupJoinRequest.DeletedAt = field.NewField(tableName, "deleted_at")
	_groupJoinRequest.SenderID = field.NewString(tableName, "sender_id")
	_groupJoinRequest.TargetGroupID = field.NewString(tableName, "target_group_id")
	_groupJoinRequest.Status = field.NewString(tableName, "status")
	_groupJoinRequest.Message = field.NewString(tableName, "message")

	_groupJoinRequest.fillFieldMap()

	return _groupJoinRequest
}

type groupJoinRequest struct {
	groupJoinRequestDo

	ALL           field.Asterisk
	ID            field.Uint
	CreatedAt     field.Time
	UpdatedAt     field.Time
	DeletedAt     field.Field
	SenderID      field.String
	TargetGroupID field.String
	Status        field.String
	Message       field.String

	fieldMap map[string]field.Expr
}

func (g groupJoinRequest) Table(newTableName string) *groupJoinRequest {
	g.groupJoinRequestDo.UseTable(newTableName)
	return g.updateTableName(newTableName)
}

func (g groupJoinRequest) As(alias string) *groupJoinRequest {
	g.groupJoinRequestDo.DO = *(g.groupJoinRequestDo.As(alias).(*gen.DO))
	return g.updateTableName(alias)
}

func (g *groupJoinRequest) updateTableName(table string) *groupJoinRequest {
	g.ALL = field.NewAsterisk(table)
	g.ID = field.NewUint(table, "id")
	g.CreatedAt = field.NewTime(table, "created_at")
	g.UpdatedAt = field.NewTime(table, "updated_at")
	g.DeletedAt = field.NewField(table, "deleted_at")
	g.SenderID = field.NewString(table, "sender_id")
	g.TargetGroupID = field.NewString(table, "target_group_id")
	g.Status = field.NewString(table, "status")
	g.Message = field.NewString(table, "message")

	g.fillFieldMap()

	return g
}

func (g *groupJoinRequest) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := g.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (g *groupJoinRequest) fillFieldMap() {
	g.fieldMap = make(map[string]field.Expr, 8)
	g.fieldMap["id"] = g.ID
	g.fieldMap["created_at"] = g.CreatedAt
	g.fieldMap["updated_at"] = g.UpdatedAt
	g.fieldMap["deleted_at"] = g.DeletedAt
	g.fieldMap["sender_id"] = g.SenderID
	g.fieldMap["target_group_id"] = g.TargetGroupID
	g.fieldMap["status"] = g.Status
	g.fieldMap["message"] = g.Message
}

func (g groupJoinRequest) clone(db *gorm.DB) groupJoinRequest {
	g.groupJoinRequestDo.ReplaceConnPool(db.Statement.ConnPool)
	return g
}

func (g groupJoinRequest) replaceDB(db *gorm.DB) groupJoinRequest {
	g.groupJoinRequestDo.ReplaceDB(db)
	return g
}

type groupJoinRequestDo struct{ gen.DO }

type IGroupJoinRequestDo interface {
	gen.SubQuery
	Debug() IGroupJoinRequestDo
	WithContext(ctx context.Context) IGroupJoinRequestDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IGroupJoinRequestDo
	WriteDB() IGroupJoinRequestDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IGroupJoinRequestDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IGroupJoinRequestDo
	Not(conds ...gen.Condition) IGroupJoinRequestDo
	Or(conds ...gen.Condition) IGroupJoinRequestDo
	Select(conds ...field.Expr) IGroupJoinRequestDo
	Where(conds ...gen.Condition) IGroupJoinRequestDo
	Order(conds ...field.Expr) IGroupJoinRequestDo
	Distinct(cols ...field.Expr) IGroupJoinRequestDo
	Omit(cols ...field.Expr) IGroupJoinRequestDo
	Join(table schema.Tabler, on ...field.Expr) IGroupJoinRequestDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IGroupJoinRequestDo
	RightJoin(table schema.Tabler, on ...field.Expr) IGroupJoinRequestDo
	Group(cols ...field.Expr) IGroupJoinRequestDo
	Having(conds ...gen.Condition) IGroupJoinRequestDo
	Limit(limit int) IGroupJoinRequestDo
	Offset(offset int) IGroupJoinRequestDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupJoinRequestDo
	Unscoped() IGroupJoinRequestDo
	Create(values ...*model.GroupJoinRequest) error
	CreateInBatches(values []*model.GroupJoinRequest, batchSize int) error
	Save(values ...*model.GroupJoinRequest) error
	First() (*model.GroupJoinRequest, error)
	Take() (*model.GroupJoinRequest, error)
	Last() (*model.GroupJoinRequest, error)
	Find() ([]*model.GroupJoinRequest, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GroupJoinRequest, err error)
	FindInBatches(result *[]*model.GroupJoinRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.GroupJoinRequest) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IGroupJoinRequestDo
	Assign(attrs ...field.AssignExpr) IGroupJoinRequestDo
	Joins(fields ...field.RelationField) IGroupJoinRequestDo
	Preload(fields ...field.RelationField) IGroupJoinRequestDo
	FirstOrInit() (*model.GroupJoinRequest, error)
	FirstOrCreate() (*model.GroupJoinRequest, error)
	FindByPage(offset int, limit int) (result []*model.GroupJoinRequest, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IGroupJoinRequestDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (g groupJoinRequestDo) Debug() IGroupJoinRequestDo {
	return g.withDO(g.DO.Debug())
}

func (g groupJoinRequestDo) WithContext(ctx context.Context) IGroupJoinRequestDo {
	return g.withDO(g.DO.WithContext(ctx))
}

func (g groupJoinRequestDo) ReadDB() IGroupJoinRequestDo {
	return g.Clauses(dbresolver.Read)
}

func (g groupJoinRequestDo) WriteDB() IGroupJoinRequestDo {
	return g.Clauses(dbresolver.Write)
}

func (g groupJoinRequestDo) Session(config *gorm.Session) IGroupJoinRequestDo {
	return g.withDO(g.DO.Session(config))
}

func (g groupJoinRequestDo) Clauses(conds ...clause.Expression) IGroupJoinRequestDo {
	return g.withDO(g.DO.Clauses(conds...))
}

func (g groupJoinRequestDo) Returning(value interface{}, columns ...string) IGroupJoinRequestDo {
	return g.withDO(g.DO.Returning(value, columns...))
}

func (g groupJoinRequestDo) Not(conds ...gen.Condition) IGroupJoinRequestDo {
	return g.withDO(g.DO.Not(conds...))
}

func (g groupJoinRequestDo) Or(conds ...gen.Condition) IGroupJoinRequestDo {
	return g.withDO(g.DO.Or(conds...))
}

func (g groupJoinRequestDo) Select(conds ...field.Expr) IGroupJoinRequestDo {
	return g.withDO(g.DO.Select(conds...))
}

func (g groupJoinRequestDo) Where(conds ...gen.Condition) IGroupJoinRequestDo {
	return g.withDO(g.DO.Where(conds...))
}

func (g groupJoinRequestDo) Order(conds ...field.Expr) IGroupJoinRequestDo {
	return g.withDO(g.DO.Order(conds...))
}

func (g groupJoinRequestDo) Distinct(cols ...field.Expr) IGroupJoinRequestDo {
	return g.withDO(g.DO.Distinct(cols...))
}

func (g groupJoinRequestDo) Omit(cols ...field.Expr) IGroupJoinRequestDo {
	return g.withDO(g.DO.Omit(cols...))
}

func (g groupJoinRequestDo) Join(table schema.Tabler, on ...field.Expr) IGroupJoinRequestDo {
	return g.withDO(g.DO.Join(table, on...))
}

func (g groupJoinRequestDo) LeftJoin(table schema.Tabler, on ...field.Expr) IGroupJoinRequestDo {
	return g.withDO(g.DO.LeftJoin(table, on...))
}

func (g groupJoinRequestDo) RightJoin(table schema.Tabler, on ...field.Expr) IGroupJoinRequestDo {
	return g.withDO(g.DO.RightJoin(table, on...))
}

func (g groupJoinRequestDo) Group(cols ...field.Expr) IGroupJoinRequestDo {
	return g.withDO(g.DO.Group(cols...))
}

func (g groupJoinRequestDo) Having(conds ...gen.Condition) IGroupJoinRequestDo {
	return g.withDO(g.DO.Having(conds...))
}

func (g groupJoinRequestDo) Limit(limit int) IGroupJoinRequestDo {
	return g.withDO(g.DO.Limit(limit))
}

func (g groupJoinRequestDo) Offset(offset int) IGroupJoinRequestDo {
	return g.withDO(g.DO.Offset(offset))
}

func (g groupJoinRequestDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IGroupJoinRequestDo {
	return g.withDO(g.DO.Scopes(funcs...))
}

func (g groupJoinRequestDo) Unscoped() IGroupJoinRequestDo {
	return g.withDO(g.DO.Unscoped())
}

func (g groupJoinRequestDo) Create(values ...*model.GroupJoinRequest) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Create(values)
}

func (g groupJoinRequestDo) CreateInBatches(values []*model.GroupJoinRequest, batchSize int) error {
	return g.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (g groupJoinRequestDo) Save(values ...*model.GroupJoinRequest) error {
	if len(values) == 0 {
		return nil
	}
	return g.DO.Save(values)
}

func (g groupJoinRequestDo) First() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) Take() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) Last() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) Find() ([]*model.GroupJoinRequest, error) {
	result, err := g.DO.Find()
	return result.([]*model.GroupJoinRequest), err
}

func (g groupJoinRequestDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.GroupJoinRequest, err error) {
	buf := make([]*model.GroupJoinRequest, 0, batchSize)
	err = g.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (g groupJoinRequestDo) FindInBatches(result *[]*model.GroupJoinRequest, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return g.DO.FindInBatches(result, batchSize, fc)
}

func (g groupJoinRequestDo) Attrs(attrs ...field.AssignExpr) IGroupJoinRequestDo {
	return g.withDO(g.DO.Attrs(attrs...))
}

func (g groupJoinRequestDo) Assign(attrs ...field.AssignExpr) IGroupJoinRequestDo {
	return g.withDO(g.DO.Assign(attrs...))
}

func (g groupJoinRequestDo) Joins(fields ...field.RelationField) IGroupJoinRequestDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Joins(_f))
	}
	return &g
}

func (g groupJoinRequestDo) Preload(fields ...field.RelationField) IGroupJoinRequestDo {
	for _, _f := range fields {
		g = *g.withDO(g.DO.Preload(_f))
	}
	return &g
}

func (g groupJoinRequestDo) FirstOrInit() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) FirstOrCreate() (*model.GroupJoinRequest, error) {
	if result, err := g.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.GroupJoinRequest), nil
	}
}

func (g groupJoinRequestDo) FindByPage(offset int, limit int) (result []*model.GroupJoinRequest, count int64, err error) {
	result, err = g.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = g.Offset(-1).Limit(-1).Count()
	return
}

func (g groupJoinRequestDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = g.Count()
	if err != nil {
		return
	}

	err = g.Offset(offset).Limit(limit).Scan(result)
	return
}

func (g groupJoinRequestDo) Scan(result interface{}) (err error) {
	return g.DO.Scan(result)
}

func (g groupJoinRequestDo) Delete(models ...*model.GroupJoinRequest) (result gen.ResultInfo, err error) {
	return g.DO.Delete(models)
}

func (g *groupJoinRequestDo) withDO(do gen.Dao) *groupJoinRequestDo {
	g.DO = *do.(*gen.DO)
	return g
}
