// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chat_backend/internal/model"
)

func newInvitationCode(db *gorm.DB, opts ...gen.DOOption) invitationCode {
	_invitationCode := invitationCode{}

	_invitationCode.invitationCodeDo.UseDB(db, opts...)
	_invitationCode.invitationCodeDo.UseModel(&model.InvitationCode{})

	tableName := _invitationCode.invitationCodeDo.TableName()
	_invitationCode.ALL = field.NewAsterisk(tableName)
	_invitationCode.ID = field.NewUint(tableName, "id")
	_invitationCode.CreatedAt = field.NewTime(tableName, "created_at")
	_invitationCode.UpdatedAt = field.NewTime(tableName, "updated_at")
	_invitationCode.DeletedAt = field.NewField(tableName, "deleted_at")
	_invitationCode.UUID = field.NewString(tableName, "uuid")
	_invitationCode.Name = field.NewString(tableName, "name")
	_invitationCode.Code = field.NewString(tableName, "code")

	_invitationCode.fillFieldMap()

	return _invitationCode
}

type invitationCode struct {
	invitationCodeDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	UUID      field.String
	Name      field.String
	Code      field.String

	fieldMap map[string]field.Expr
}

func (i invitationCode) Table(newTableName string) *invitationCode {
	i.invitationCodeDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i invitationCode) As(alias string) *invitationCode {
	i.invitationCodeDo.DO = *(i.invitationCodeDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *invitationCode) updateTableName(table string) *invitationCode {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewUint(table, "id")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")
	i.DeletedAt = field.NewField(table, "deleted_at")
	i.UUID = field.NewString(table, "uuid")
	i.Name = field.NewString(table, "name")
	i.Code = field.NewString(table, "code")

	i.fillFieldMap()

	return i
}

func (i *invitationCode) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *invitationCode) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 7)
	i.fieldMap["id"] = i.ID
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
	i.fieldMap["deleted_at"] = i.DeletedAt
	i.fieldMap["uuid"] = i.UUID
	i.fieldMap["name"] = i.Name
	i.fieldMap["code"] = i.Code
}

func (i invitationCode) clone(db *gorm.DB) invitationCode {
	i.invitationCodeDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i invitationCode) replaceDB(db *gorm.DB) invitationCode {
	i.invitationCodeDo.ReplaceDB(db)
	return i
}

type invitationCodeDo struct{ gen.DO }

type IInvitationCodeDo interface {
	gen.SubQuery
	Debug() IInvitationCodeDo
	WithContext(ctx context.Context) IInvitationCodeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInvitationCodeDo
	WriteDB() IInvitationCodeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInvitationCodeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInvitationCodeDo
	Not(conds ...gen.Condition) IInvitationCodeDo
	Or(conds ...gen.Condition) IInvitationCodeDo
	Select(conds ...field.Expr) IInvitationCodeDo
	Where(conds ...gen.Condition) IInvitationCodeDo
	Order(conds ...field.Expr) IInvitationCodeDo
	Distinct(cols ...field.Expr) IInvitationCodeDo
	Omit(cols ...field.Expr) IInvitationCodeDo
	Join(table schema.Tabler, on ...field.Expr) IInvitationCodeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInvitationCodeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInvitationCodeDo
	Group(cols ...field.Expr) IInvitationCodeDo
	Having(conds ...gen.Condition) IInvitationCodeDo
	Limit(limit int) IInvitationCodeDo
	Offset(offset int) IInvitationCodeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInvitationCodeDo
	Unscoped() IInvitationCodeDo
	Create(values ...*model.InvitationCode) error
	CreateInBatches(values []*model.InvitationCode, batchSize int) error
	Save(values ...*model.InvitationCode) error
	First() (*model.InvitationCode, error)
	Take() (*model.InvitationCode, error)
	Last() (*model.InvitationCode, error)
	Find() ([]*model.InvitationCode, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InvitationCode, err error)
	FindInBatches(result *[]*model.InvitationCode, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.InvitationCode) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInvitationCodeDo
	Assign(attrs ...field.AssignExpr) IInvitationCodeDo
	Joins(fields ...field.RelationField) IInvitationCodeDo
	Preload(fields ...field.RelationField) IInvitationCodeDo
	FirstOrInit() (*model.InvitationCode, error)
	FirstOrCreate() (*model.InvitationCode, error)
	FindByPage(offset int, limit int) (result []*model.InvitationCode, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInvitationCodeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i invitationCodeDo) Debug() IInvitationCodeDo {
	return i.withDO(i.DO.Debug())
}

func (i invitationCodeDo) WithContext(ctx context.Context) IInvitationCodeDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i invitationCodeDo) ReadDB() IInvitationCodeDo {
	return i.Clauses(dbresolver.Read)
}

func (i invitationCodeDo) WriteDB() IInvitationCodeDo {
	return i.Clauses(dbresolver.Write)
}

func (i invitationCodeDo) Session(config *gorm.Session) IInvitationCodeDo {
	return i.withDO(i.DO.Session(config))
}

func (i invitationCodeDo) Clauses(conds ...clause.Expression) IInvitationCodeDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i invitationCodeDo) Returning(value interface{}, columns ...string) IInvitationCodeDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i invitationCodeDo) Not(conds ...gen.Condition) IInvitationCodeDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i invitationCodeDo) Or(conds ...gen.Condition) IInvitationCodeDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i invitationCodeDo) Select(conds ...field.Expr) IInvitationCodeDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i invitationCodeDo) Where(conds ...gen.Condition) IInvitationCodeDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i invitationCodeDo) Order(conds ...field.Expr) IInvitationCodeDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i invitationCodeDo) Distinct(cols ...field.Expr) IInvitationCodeDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i invitationCodeDo) Omit(cols ...field.Expr) IInvitationCodeDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i invitationCodeDo) Join(table schema.Tabler, on ...field.Expr) IInvitationCodeDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i invitationCodeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInvitationCodeDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i invitationCodeDo) RightJoin(table schema.Tabler, on ...field.Expr) IInvitationCodeDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i invitationCodeDo) Group(cols ...field.Expr) IInvitationCodeDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i invitationCodeDo) Having(conds ...gen.Condition) IInvitationCodeDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i invitationCodeDo) Limit(limit int) IInvitationCodeDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i invitationCodeDo) Offset(offset int) IInvitationCodeDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i invitationCodeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInvitationCodeDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i invitationCodeDo) Unscoped() IInvitationCodeDo {
	return i.withDO(i.DO.Unscoped())
}

func (i invitationCodeDo) Create(values ...*model.InvitationCode) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i invitationCodeDo) CreateInBatches(values []*model.InvitationCode, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i invitationCodeDo) Save(values ...*model.InvitationCode) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i invitationCodeDo) First() (*model.InvitationCode, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.InvitationCode), nil
	}
}

func (i invitationCodeDo) Take() (*model.InvitationCode, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.InvitationCode), nil
	}
}

func (i invitationCodeDo) Last() (*model.InvitationCode, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.InvitationCode), nil
	}
}

func (i invitationCodeDo) Find() ([]*model.InvitationCode, error) {
	result, err := i.DO.Find()
	return result.([]*model.InvitationCode), err
}

func (i invitationCodeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.InvitationCode, err error) {
	buf := make([]*model.InvitationCode, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i invitationCodeDo) FindInBatches(result *[]*model.InvitationCode, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i invitationCodeDo) Attrs(attrs ...field.AssignExpr) IInvitationCodeDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i invitationCodeDo) Assign(attrs ...field.AssignExpr) IInvitationCodeDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i invitationCodeDo) Joins(fields ...field.RelationField) IInvitationCodeDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i invitationCodeDo) Preload(fields ...field.RelationField) IInvitationCodeDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i invitationCodeDo) FirstOrInit() (*model.InvitationCode, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.InvitationCode), nil
	}
}

func (i invitationCodeDo) FirstOrCreate() (*model.InvitationCode, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.InvitationCode), nil
	}
}

func (i invitationCodeDo) FindByPage(offset int, limit int) (result []*model.InvitationCode, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i invitationCodeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i invitationCodeDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i invitationCodeDo) Delete(models ...*model.InvitationCode) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *invitationCodeDo) withDO(do gen.Dao) *invitationCodeDo {
	i.DO = *do.(*gen.DO)
	return i
}
