// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"chat_backend/internal/model"
)

func newMessageReceipt(db *gorm.DB, opts ...gen.DOOption) messageReceipt {
	_messageReceipt := messageReceipt{}

	_messageReceipt.messageReceiptDo.UseDB(db, opts...)
	_messageReceipt.messageReceiptDo.UseModel(&model.MessageReceipt{})

	tableName := _messageReceipt.messageReceiptDo.TableName()
	_messageReceipt.ALL = field.NewAsterisk(tableName)
	_messageReceipt.MessageID = field.NewString(tableName, "message_id")
	_messageReceipt.UserID = field.NewString(tableName, "user_id")
	_messageReceipt.IsDelivered = field.NewBool(tableName, "is_delivered")
	_messageReceipt.CreatedAt = field.NewTime(tableName, "created_at")

	_messageReceipt.fillFieldMap()

	return _messageReceipt
}

type messageReceipt struct {
	messageReceiptDo

	ALL         field.Asterisk
	MessageID   field.String
	UserID      field.String
	IsDelivered field.Bool
	CreatedAt   field.Time

	fieldMap map[string]field.Expr
}

func (m messageReceipt) Table(newTableName string) *messageReceipt {
	m.messageReceiptDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m messageReceipt) As(alias string) *messageReceipt {
	m.messageReceiptDo.DO = *(m.messageReceiptDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *messageReceipt) updateTableName(table string) *messageReceipt {
	m.ALL = field.NewAsterisk(table)
	m.MessageID = field.NewString(table, "message_id")
	m.UserID = field.NewString(table, "user_id")
	m.IsDelivered = field.NewBool(table, "is_delivered")
	m.CreatedAt = field.NewTime(table, "created_at")

	m.fillFieldMap()

	return m
}

func (m *messageReceipt) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *messageReceipt) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 4)
	m.fieldMap["message_id"] = m.MessageID
	m.fieldMap["user_id"] = m.UserID
	m.fieldMap["is_delivered"] = m.IsDelivered
	m.fieldMap["created_at"] = m.CreatedAt
}

func (m messageReceipt) clone(db *gorm.DB) messageReceipt {
	m.messageReceiptDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m messageReceipt) replaceDB(db *gorm.DB) messageReceipt {
	m.messageReceiptDo.ReplaceDB(db)
	return m
}

type messageReceiptDo struct{ gen.DO }

type IMessageReceiptDo interface {
	gen.SubQuery
	Debug() IMessageReceiptDo
	WithContext(ctx context.Context) IMessageReceiptDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMessageReceiptDo
	WriteDB() IMessageReceiptDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMessageReceiptDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMessageReceiptDo
	Not(conds ...gen.Condition) IMessageReceiptDo
	Or(conds ...gen.Condition) IMessageReceiptDo
	Select(conds ...field.Expr) IMessageReceiptDo
	Where(conds ...gen.Condition) IMessageReceiptDo
	Order(conds ...field.Expr) IMessageReceiptDo
	Distinct(cols ...field.Expr) IMessageReceiptDo
	Omit(cols ...field.Expr) IMessageReceiptDo
	Join(table schema.Tabler, on ...field.Expr) IMessageReceiptDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMessageReceiptDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMessageReceiptDo
	Group(cols ...field.Expr) IMessageReceiptDo
	Having(conds ...gen.Condition) IMessageReceiptDo
	Limit(limit int) IMessageReceiptDo
	Offset(offset int) IMessageReceiptDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMessageReceiptDo
	Unscoped() IMessageReceiptDo
	Create(values ...*model.MessageReceipt) error
	CreateInBatches(values []*model.MessageReceipt, batchSize int) error
	Save(values ...*model.MessageReceipt) error
	First() (*model.MessageReceipt, error)
	Take() (*model.MessageReceipt, error)
	Last() (*model.MessageReceipt, error)
	Find() ([]*model.MessageReceipt, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MessageReceipt, err error)
	FindInBatches(result *[]*model.MessageReceipt, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MessageReceipt) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMessageReceiptDo
	Assign(attrs ...field.AssignExpr) IMessageReceiptDo
	Joins(fields ...field.RelationField) IMessageReceiptDo
	Preload(fields ...field.RelationField) IMessageReceiptDo
	FirstOrInit() (*model.MessageReceipt, error)
	FirstOrCreate() (*model.MessageReceipt, error)
	FindByPage(offset int, limit int) (result []*model.MessageReceipt, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMessageReceiptDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m messageReceiptDo) Debug() IMessageReceiptDo {
	return m.withDO(m.DO.Debug())
}

func (m messageReceiptDo) WithContext(ctx context.Context) IMessageReceiptDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m messageReceiptDo) ReadDB() IMessageReceiptDo {
	return m.Clauses(dbresolver.Read)
}

func (m messageReceiptDo) WriteDB() IMessageReceiptDo {
	return m.Clauses(dbresolver.Write)
}

func (m messageReceiptDo) Session(config *gorm.Session) IMessageReceiptDo {
	return m.withDO(m.DO.Session(config))
}

func (m messageReceiptDo) Clauses(conds ...clause.Expression) IMessageReceiptDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m messageReceiptDo) Returning(value interface{}, columns ...string) IMessageReceiptDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m messageReceiptDo) Not(conds ...gen.Condition) IMessageReceiptDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m messageReceiptDo) Or(conds ...gen.Condition) IMessageReceiptDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m messageReceiptDo) Select(conds ...field.Expr) IMessageReceiptDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m messageReceiptDo) Where(conds ...gen.Condition) IMessageReceiptDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m messageReceiptDo) Order(conds ...field.Expr) IMessageReceiptDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m messageReceiptDo) Distinct(cols ...field.Expr) IMessageReceiptDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m messageReceiptDo) Omit(cols ...field.Expr) IMessageReceiptDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m messageReceiptDo) Join(table schema.Tabler, on ...field.Expr) IMessageReceiptDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m messageReceiptDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMessageReceiptDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m messageReceiptDo) RightJoin(table schema.Tabler, on ...field.Expr) IMessageReceiptDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m messageReceiptDo) Group(cols ...field.Expr) IMessageReceiptDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m messageReceiptDo) Having(conds ...gen.Condition) IMessageReceiptDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m messageReceiptDo) Limit(limit int) IMessageReceiptDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m messageReceiptDo) Offset(offset int) IMessageReceiptDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m messageReceiptDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMessageReceiptDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m messageReceiptDo) Unscoped() IMessageReceiptDo {
	return m.withDO(m.DO.Unscoped())
}

func (m messageReceiptDo) Create(values ...*model.MessageReceipt) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m messageReceiptDo) CreateInBatches(values []*model.MessageReceipt, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m messageReceiptDo) Save(values ...*model.MessageReceipt) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m messageReceiptDo) First() (*model.MessageReceipt, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageReceipt), nil
	}
}

func (m messageReceiptDo) Take() (*model.MessageReceipt, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageReceipt), nil
	}
}

func (m messageReceiptDo) Last() (*model.MessageReceipt, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageReceipt), nil
	}
}

func (m messageReceiptDo) Find() ([]*model.MessageReceipt, error) {
	result, err := m.DO.Find()
	return result.([]*model.MessageReceipt), err
}

func (m messageReceiptDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MessageReceipt, err error) {
	buf := make([]*model.MessageReceipt, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m messageReceiptDo) FindInBatches(result *[]*model.MessageReceipt, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m messageReceiptDo) Attrs(attrs ...field.AssignExpr) IMessageReceiptDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m messageReceiptDo) Assign(attrs ...field.AssignExpr) IMessageReceiptDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m messageReceiptDo) Joins(fields ...field.RelationField) IMessageReceiptDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m messageReceiptDo) Preload(fields ...field.RelationField) IMessageReceiptDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m messageReceiptDo) FirstOrInit() (*model.MessageReceipt, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageReceipt), nil
	}
}

func (m messageReceiptDo) FirstOrCreate() (*model.MessageReceipt, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MessageReceipt), nil
	}
}

func (m messageReceiptDo) FindByPage(offset int, limit int) (result []*model.MessageReceipt, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m messageReceiptDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m messageReceiptDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m messageReceiptDo) Delete(models ...*model.MessageReceipt) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *messageReceiptDo) withDO(do gen.Dao) *messageReceiptDo {
	m.DO = *do.(*gen.DO)
	return m
}
